### ISSUE TITLE
[FIXED] Autostart issue

### ISSUE THREAD

**Issue by dhruvdutt** [Hikari9/comfortable-swipe#11]
```
$ comfortable-swipe autostart
Autostart switched on
```
Tried using autostart command but it doesn't run automatically on startup.

I also had to fix permissions in `/dev/input/event*` to make the program run normally.

OS: Ubuntu 16.04 (64-bit)
Kernel version: 4.10.0-38-generic
KDE neon: 5.11
Plasma version: 5.11.2

**Comment by Hikari9** [comment]
Can you run `gnome-session-properties` and check if Comfortable Swipe is in one of the entries?

**Comment by dhruvdutt** [comment]
@Hikari9 I'm using KDE 5.11
The KDE equivalent of that command seems to be [`$HOME/.config/autostart`](https://docs.kde.org/trunk5/en/kde-workspace/kcontrol/autostart/index.html).

![image](https://user-images.githubusercontent.com/5961873/32431328-1c637ee8-c2f9-11e7-8d53-a6fee68e8ef7.png)

**Comment by Hikari9** [comment]
That's weird, KDE should allow `.desktop` files by default, even if they're not executable. Can you run:

```
sed -i "s|Exec=.*|Exec=comfortable-swipe start 2> ~/Desktop/comfortable-swipe.log|g" ~/.config/autostart/comfortable-swipe.desktop
```

then log out / log back in, and show the output of `~/Desktop/comfortable-swipe.log`? The above script activates error-logging to the autostart.

**Comment by dhruvdutt** [comment]
The log file says
```
/bin/sh: 1: comfortable-swipe: not found
```
The same command works with my terminal/shell. I'm using zsh. Not using the default bash shell.

My [.zshrc](https://gist.github.com/dhruvdutt/a3100d8e2a15ad5d105295ae8d4ebeac), [.bashrc](https://gist.github.com/dhruvdutt/eb34e29e50509dd30f7e5d686ce073bd)

**Comment by Hikari9** [comment]
@dhruvdutt looks like that PATH does not load early for some reason in KDE startup when using `.zsrhc`. Attempted to fix it by directly calling bash with absolute path in the autostart script.

Please see if PR #12 fixes the problem, will merge once you confirm that it works :)

(checkout branch [bugfix-kde-startup](https://github.com/Hikari9/comfortable-swipe-ubuntu/tree/bugfix-kde-startup), `bash install`, log out / log back in)

**Comment by dhruvdutt** [comment]
Awesome. It works! :rocket: :rocket:

**Comment by Hikari9** [comment]
Great! Marking this as fixed.
