### ISSUE TITLE
Auto start is not working

### ISSUE THREAD

**Issue by hashemirafsan** [Hikari9/comfortable-swipe#13]
i clone your your project and it's so damn good but you had offered for auto start command but it doesn't work

**Comment by Hikari9** [comment]
Oh no. What's your desktop configuration? Please comment result of:
```
lsb_release -a
```

**Comment by Hikari9** [comment]
Also, does the output toggle between `Autostart switched off` and `Autostart switched on` in the terminal when you run `comfortable-swipe autostart`?

**Comment by pavel-kalmykov** [comment]
I have the same issue, I run it with sudo if that matters at all. The message yelling whether it's on or off works, by the way. My `lsb_release -a`:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

I would've installed 17.10 but it gave some error so I switched back to the last version.

Maybe implementing #7 would solve the issue, and BTW I think it would be better :+1:

**Comment by Hikari9** [comment]
For now, autostart only works if you did `bash install` without sudo. I'm still figuring out how to do systemd service with `libinput`, still tracking some problems since not all variables are present in PATH in systemctl... 

If anyone has good grasp about systemctl services and willing to contribute, that would help greatly!

**Comment by Hikari9** [comment]
@hashemirafsan @paveltrufi Please check out PR #15, if it fixes the issue. Instructions on how to test are located there. Thanks!

**Comment by Hikari9** [comment]
Sorry, I was not able to finish the `systemd` service for this. I know this issue is old, but I want to report some updates.

A workaround I'm thinking of is to add `sleep` in the startup application before booting comfortable swipe. Try running this and tell me if it works:

```bash
mkdir -p ~/.config/autostart
echo '[Desktop Entry]
Type=Application
Exec=bash -c "/bin/sleep 3 && /usr/local/bin/comfortable-swipe start"
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Comfortable Swipe
Comment=3 or 4 touchpad gestures' > ~/.config/autostart
```

**Comment by Hikari9** [comment]
Closing this because autostart is now working as of v1.0.1. Please check out the repository and perform the installation steps again.

**Comment by pavel-kalmykov** [comment]
Hi. I'm sorry but I don't use this program anymore. I'm glad you were able to solve it anyway!

**Comment by Lightras** [comment]
> Sorry, I was not able to finish the `systemd` service for this. I know this issue is old, but I want to report some updates.
> 
> A workaround I'm thinking of is to add `sleep` in the startup application before booting comfortable swipe. Try running this and tell me if it works:
> 
> ```shell
> mkdir -p ~/.config/autostart
> echo '[Desktop Entry]
> Type=Application
> Exec=bash -c "/bin/sleep 3 && /usr/local/bin/comfortable-swipe start"
> Hidden=false
> NoDisplay=false
> X-GNOME-Autostart-enabled=true
> Name=Comfortable Swipe
> Comment=3 or 4 touchpad gestures' > ~/.config/autostart
> ```

this worked for me, thanks!
(I had autostart not working on v1.0.4)
