### ISSUE TITLE
Execution (or recognition) delay

### ISSUE THREAD

**Issue by schigum** [Hikari9/comfortable-swipe#16]
Hey, thanks so much for providing this.
It is exactly what I was looking for. 

I'm running this on Ubuntu 17.10.
One oddity I noticed is that I have a delay of ~1s before the swipe gets executed and the output in console appears (e.g. SWIPE down 4).
So I (quickly) swipe, take the fingers of the pad and after about 1s it gets executed.
The main question is, is that normal? And can anything be done about that?

Thanks and cheers!

**Comment by Hikari9** [comment]
@schigum yeah the 1s delay was intentional. The full answer is in PR #15 as it hasn't been merged yet to master. Please make further comments in the PR, thanks!

**Comment by Hikari9** [comment]
My bad, @schigum clarified that this problem has nothing to do with PR #15, hence I'm reopening this issue.

**Comment by Hikari9** [comment]
As a follow-up, I think that the delay you're experiencing is either a one-time thing or has something to do with loading `libinput-debug-events` or another external application not with comfortable-swipe itself. Try running
```
bash install && comfortable-swipe start
```

Does the issue still persist?

**Comment by schigum** [comment]
I agree, it is not related to comfortable-swipe itself.
I just found by accident while trying to record it that this delay disappears if I use the German keyboard layout instead of the English layout.
Switching back to English also brings back the delay...

When I have a bit more time later today I'll see whether this is connected to what kind of key bindings I set (at the moment it's <super>+W|A|S|D).

Thanks so much,
schigum

**Comment by schigum** [comment]
Ok, just to summarize,
Any layout that is not the first entry in the list of input sources (in the "region and language" settings) has this delay. So changing the order allows to choose where to have the delay.
I have no idea how or why, but as it is now it provides an acceptable workaround for me.

Thanks and cheers,
Schigum

**Comment by Hikari9** [comment]
Glad you found a workaround. Apparently it's a new problem in 17.10 (askubuntu article: [Keyboard input lags](https://askubuntu.com/questions/968788/keyboard-input-lags-on-ubuntu-17-10)). I guess we'll just have to wait for a dist update for a fix.

Closing this issue for now.
