### ISSUE TITLE
The Config File Can't be found

### ISSUE THREAD

**Issue by HadiLatifi** [Hikari9/comfortable-swipe#20]
The config file is not located in `/usr/share/comfortable-swipe/comfortable-swipe.conf`
going through commits found it's in `~/.config/comfortable-swipe.conf`
I'm running **Kubuntu 17.04** and recently installed this app.
Updating the **readme** file can be helpful

**Comment by Hikari9** [comment]
@HadiLatifi My bad, thanks for pointing it out.

Like you said, the readme was wrong. It's supposed to be in `/usr/local/share/comfortable-swipe/comfortable-swipe.conf`. Merged new **readme** in PR #21.
