### ISSUE TITLE
Three tap middle click not working

### ISSUE THREAD

**Issue by SiddharthPant** [Hikari9/comfortable-swipe#22]
After enabling comfortable swipe 3-tap middle clicking stops working. Could you introduce a configuration so that if the user just taps not swipes he can middle click instead of swiping. I activated middle clicking before using the below commands. Note that right now my 3-taps do not register as middle clicks:
```
cd ~/
echo "synclient TapButton3=2" > touchpad.sh
chmod +x .touchpad.sh
gsettings set org.gnome.settings-daemon.peripherals.input-devices hotplug-command “$HOME/.touchpad.sh”
```

**Comment by Hikari9** [comment]
you can change increase the threshold value found in `/usr/local/share/comfortable-swipe/comfortable-swipe.conf`

**Comment by SiddharthPant** [comment]
I tried upto 0.9 didn't have any effect I will try with more greater values

**Comment by SiddharthPant** [comment]
What is the unit of threshold being used here? Is it milliseconds or in seconds?

**Comment by Hikari9** [comment]
It's in mouse pixels, so it depends on your touchpad DPI. Can you try values greater than 1? For example try 20.0

**Comment by SiddharthPant** [comment]
Ok that is interesting. Anyways problem solved. It is not related to threshold. For some reason the script I am trying to execute on start using gsettings does not run. I tried running it using .bashrc and its working now. So I am happy and this issue can be closed now.

**Comment by Hikari9** [comment]
Interesting. Thanks!
