### ISSUE TITLE
Don't works Tab's alias

### ISSUE THREAD

**Issue by nandolopez** [Hikari9/comfortable-swipe#25]
Hi!.
I try to map to three fingers left or three fingers right, the Alt+Tab+Left, and Alt+tab+Right and doesn't works ¿any idea?

**Comment by Hikari9** [comment]
@FernanLM88, Alt+Tab+Right and Alt+Tab+Left works for me. The config should look like this:

```
# /usr/local/share/comfortable-swipe.conf

left3 = Alt+Tab+Left
right3 = Alt+Tab+Right
```

Make sure the capitalization is correct, and to run `comfortable-swipe restart` after modification. Please tell me if it works.

If it doesn't, please paste the output when you perform gestures after running `comfortable-swipe start` in the terminal.

**Comment by Hikari9** [comment]
@NandoLopez any updates?

**Comment by Hikari9** [comment]
Closing and marking as deprecated since issue is more than a year old.
