### ISSUE TITLE
Installation aborted

### ISSUE THREAD

**Issue by maeckha** [Hikari9/comfortable-swipe#27]
Hello, i followed your readme until the *bash install* part. 
When I am trying to install, the terminal says ```sudo: g++: command not found``` and aborts the installation. 
Do you have any advice for this kind of problem? 
Thanks in advance!

**Comment by EricWRogers** [comment]
if your on ubuntu 
sudo apt-get install g++ gcc
that should fix it

**Comment by maeckha** [comment]
Thanks! That worked.
