### ISSUE TITLE
gesture inputs a character when first time used

### ISSUE THREAD

**Issue by Maik93** [Hikari9/comfortable-swipe#35]
Hi, beautiful work so far!
However there's an annoying thing that sometimes happen:
when it's a while that I don't make any gesture, the first one that I do is incorrectly interpreted as a character, writing 'A' (if I swipe up) or 'B' (if I swipe down) in any input text currently on focus (chrome, terminal, everything); repeating the gesture immediately after triggers the desired behaviour.

Here's my configurations:
> threshold = 0.0
> left3 = shift+alt+Tab
> left4 = ctrl+alt+shift+Right
> right3 = alt+Tab
> right4 = ctrl+alt+shift+Left
> up3 = ctrl+alt+Down
> up4 = ctrl+alt+shift+Down
> down3 = ctrl+alt+Up
> down4 = ctrl+alt+shift+Up

All of them has this behaviour, prompting different characters.

Running Ubuntu 18.04 LTS

**Comment by Hikari9** [comment]
Hi @Maik93 , I have confirmed your issue.

This may be a known bug if you're using `synclient` (see [here](https://ubuntuforums.org/showthread.php?t=1607973)). Try:
```
synclient TapButton3=2
```

**Check first if it works**. If it does, make sure you run this every time during startup.
In your Dash, type "Startup Applications", then click "Add":

![image](https://user-images.githubusercontent.com/5916118/52391719-b685c280-2ad9-11e9-843a-aa95d0121ccd.png)


If the above does not work, please paste your output when you run this:
```
synclient
```

**Comment by Maik93** [comment]
Sorry to replying only now, I don't have `synclient` installed (command not found)... Do you suggest to install it and add that command to startup applications?

**Comment by Hikari9** [comment]
No, don't do that, it was just a solution if you're using `synclient`. Since you're not, you may ignore it.

But I'll let you know that `comfortable-swipe` has been updated to a new version. You can clone and run `bash install` again to see if issue has been solved by the update.

**Comment by Maik93** [comment]
I've updated 3 days ago and used gestures for a while, it seems that the problem is solved, thank you!
