### ISSUE TITLE
Gesture not responding randomly

### ISSUE THREAD

**Issue by Nayananga** [Hikari9/comfortable-swipe#36]
I`m using ubuntu 18.10. I did follow steps as exactly are they mentioned in the readme.md. comfortable-swipe works, but sometime it won`t work randomly. when I try several times may be with 3 fingers and also 4 figures then sometimes it works agairandomlurandomlun.but it works somehow again so I didn`t want to restart.

**Comment by Hikari9** [comment]
Maybe the config is not very sensitive? Have you tried tweaking `comfortable-swipe.conf` and set threshold to a small number

**Comment by Nayananga** [comment]
I moved to [https://github.com/iberianpig/fusuma](url) in that config file I did reduce the threshold to 0.1 and it is working fine. I think the solution to this issue might exact same so I`m closing the issue.
