### ISSUE TITLE
cant get it to work - permission problem?

### ISSUE THREAD

**Issue by websvcPT** [Hikari9/comfortable-swipe#4]
Hi, 
First of all, You seem to have a great job here!

Here goes my issue.
Despiste following instructions I get the permission denied message and a regex error as well

```
$ comfortable-swipe start

terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted
Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event15 (Permission denied)
Failed to open /dev/input/event16 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event11 (Permission denied)
Failed to open /dev/input/event12 (Permission denied)
Failed to open /dev/input/event13 (Permission denied)
Failed to open /dev/input/event14 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Failed to open /dev/input/event3 (Permission denied)
Expected device added events on startup but got none. Maybe you don't have the right permissions?
```

Also I've added a symmlink from /home/$USER/.local/bin/comfortable-swipe to /usr/bin/ for 

I'm using Linux mint 17 (Ubuntu Xenial)
```
$ uname .a  
Linux rog1 4.4.0-70-generic #91~14.04.1-Ubuntu SMP Wed Mar 22 15:48:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Hikari9** [comment]
Maybe your input permission group has different name. Try running `ls -l /dev/input/event*` in terminal, should look something like this:
```
$ ls -l /dev/input/event*

crw-rw---- 1 root input 13, 64 Oct 23 13:00 /dev/input/event0
crw-rw---- 1 root input 13, 65 Oct 23 13:00 /dev/input/event1
crw-rw---- 1 root input 13, 74 Oct 23 13:00 /dev/input/event10
crw-rw---- 1 root input 13, 75 Oct 23 13:00 /dev/input/event11
crw-rw---- 1 root input 13, 76 Oct 23 13:00 /dev/input/event12
crw-rw---- 1 root input 13, 77 Oct 23 13:00 /dev/input/event13
crw-rw---- 1 root input 13, 78 Oct 23 13:00 /dev/input/event14
```
Observe in 4th column that permission group is `input`, then allow permissions for user by running:
```
$ sudo gpasswd -a $USER input

[sudo] password for hikari:
Adding user hikari to group input
```

Replace `input` by whatever is applicable (usually `input` or `evdev`, can be different between distros).

**Comment by Hikari9** [comment]
Also, it is more recommended to add `/home/$USER/.local/bin/` to your user's PATH than adding a symlink to a global folder like `/usr/bin`. Consider adding the following line:

```
export PATH="$PATH:/home/$USER/.local/bin"
```

to your `~/.bashrc` or `~/.zshrc`, whichever is appropriate.

Will close this issue for now. Please reopen if there are still issues even with the solutions above.

**Comment by shivdhwaj** [comment]
Unable to solve this issue with after adding the user to input group in Ubuntu 18

**Comment by Hikari9** [comment]
@shivdhwaj , Is this Ubuntu 18.10? Have you tried logging out/logging in or rebooting?

As of version [v1.0.2](https://github.com/Hikari9/comfortable-swipe/releases), comfortable swipe is now located at `/usr/local/bin/comfortable-swipe`. 

Can you try pasting the output of the following:

1. `lsb_release -a`
2. `which comfortable-swipe`
3. `ls /usr/local/bin/comfortable-swipe`
4. `ls -l /dev/input/event*`

**Comment by shivdhwaj** [comment]
@Hikari9 Ubuntu 18.04 LTS
Outputs:
**lsb_release -a** 
> No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**which comfortable-swipe**
> /usr/local/bin/comfortable-swipe

**ls /usr/local/bin/comfortable-swipe**
> /usr/local/bin/comfortable-swipe

**ls -l /dev/input/event***
>crw-rw---- 1 root input 13, 64 Mar 15 10:19 /dev/input/event0
crw-rw---- 1 root input 13, 65 Mar 15 10:19 /dev/input/event1
crw-rw---- 1 root input 13, 74 Mar 15 10:19 /dev/input/event10
crw-rw---- 1 root input 13, 75 Mar 15 10:19 /dev/input/event11
crw-rw---- 1 root input 13, 76 Mar 15 10:19 /dev/input/event12
crw-rw---- 1 root input 13, 77 Mar 15 10:19 /dev/input/event13
crw-rw---- 1 root input 13, 78 Mar 15 10:19 /dev/input/event14
crw-rw---- 1 root input 13, 79 Mar 15 10:19 /dev/input/event15
crw-rw---- 1 root input 13, 80 Mar 15 10:19 /dev/input/event16
crw-rw---- 1 root input 13, 66 Mar 15 10:19 /dev/input/event2
crw-rw---- 1 root input 13, 67 Mar 15 10:19 /dev/input/event3
crw-rw---- 1 root input 13, 68 Mar 15 10:19 /dev/input/event4
crw-rw---- 1 root input 13, 69 Mar 15 10:19 /dev/input/event5
crw-rw---- 1 root input 13, 70 Mar 15 10:19 /dev/input/event6
crw-rw---- 1 root input 13, 71 Mar 15 10:19 /dev/input/event7
crw-rw---- 1 root input 13, 72 Mar 15 10:19 /dev/input/event8
crw-rw---- 1 root input 13, 73 Mar 15 10:19 /dev/input/event9

**Comment by Hikari9** [comment]
The input group seems to have no problem... Can you give me the output of

- `comfortable-swipe status`
- `comfortable-swipe start` (try swiping if you can see SWIPE XXX)
- `comfortable-swipe debug` (try swiping if you can see GESTURE_SWIPE_XXX)
- `cat $(comfortable-swipe config)`

Also some miscellaneous things that might help
- `libinput --version`
- `g++ --version`
- `xinput | grep hid`

**Comment by shivdhwaj** [comment]
Changes the commands in config as per the shortcuts of 18.04 and rebooted system its working as only tried one command right now

**Comment by Hikari9** [comment]
Ok thank you. Closing this issue as it seems to be fixed. Just reopen if you have more concerns :)
