### ISSUE TITLE
Gesture detected but nothing happend after

### ISSUE THREAD

**Issue by nakrule** [Hikari9/comfortable-swipe#57]
Hi, when I start the program, it looks to detect my gestures:

	$ comfortable-swipe start
	^[[1;7BSWIPE up3
	SWIPE down3
	^[[1;7ASWIPE right3
	SWIPE left3
	SWIPE down4
	SWIPE up4
	SWIPE right4
	SWIPE left4
	SWIPE right4
	SWIPE right4
	SWIPE right4

The command `debug` give me the following output for a single scroll:

	-event6   GESTURE_SWIPE_BEGIN  +3.33s	3
	 event6   GESTURE_SWIPE_UPDATE  +3.33s	3 -8.09/ 0.90 (-29.53/ 3.28 unaccelerated)
	 event6   GESTURE_SWIPE_UPDATE  +3.34s	3 -12.17/ 0.41 (-32.81/ 1.09 unaccelerated)
	 event6   GESTURE_SWIPE_UPDATE  +3.35s	3 -12.58/ 1.22 (-33.90/ 3.28 unaccelerated)
	 event6   GESTURE_SWIPE_UPDATE  +3.35s	3 -13.39/ 2.43 (-36.09/ 6.56 unaccelerated)
	 event6   GESTURE_SWIPE_UPDATE  +3.36s	3 -12.17/ 2.43 (-32.81/ 6.56 unaccelerated)
	 event6   GESTURE_SWIPE_UPDATE  +3.37s	3 -10.14/ 2.03 (-27.34/ 5.47 unaccelerated)
	 event6   GESTURE_SWIPE_UPDATE  +3.38s	3 -10.14/ 1.62 (-27.34/ 4.37 unaccelerated)
	^[[1;7C event6   GESTURE_SWIPE_UPDATE  +3.38s	3 -5.68/ 0.81 (-15.31/ 2.19 unaccelerated)
	 event6   GESTURE_SWIPE_UPDATE  +3.39s	3 -3.65/ 0.41 (-9.84/ 1.09 unaccelerated)
	 event6   GESTURE_SWIPE_UPDATE  +3.40s	3 -3.25/ 0.00 (-8.75/ 0.00 unaccelerated)
	 event6   GESTURE_SWIPE_END  +3.42s	3

I assume it detect my gestures, but it does not switch me to another desktop with 3 fingers gesture nor does it move the current active windows with 4 fingers gesture. I use Ubuntu 18.04.1 LTS with a Razer Blade 15 and the default config file.

**Comment by Hikari9** [comment]
You're right. Based on your output `comfortable-swipe` works fine, so I'm closing the issue.

I suspect your **workspaces** may not be enabled.
Try this http://ubuntuhandbook.org/index.php/2013/07/enable-workspaces-on-ubuntu-unity/

**Comment by nakrule** [comment]
Workspace are activate by default on Ubuntu 18.x and works fine on my computer (using the default Ubuntu shortcut). That should not be the problem.

**Comment by Hikari9** [comment]
OK, reopening this issue.

`comfortable-swipe` relies on **keyboard shortcuts** to activate workspaces. If you have custom keyboard shortcuts for switching, I suggest you edit the config file.

Run this to show your config:
```bash
cat $(comfortable-swipe config) | grep -vE "#|^$"
```

Output can be something like:
```
threshold = 0.0
left3 = ctrl+alt+Right
left4 = ctrl+alt+shift+Right
right3 = ctrl+alt+Left
right4 = ctrl+alt+shift+Left
up3 = ctrl+alt+Down
up4 = ctrl+alt+shift+Down
down3 = ctrl+alt+Up
down4 = ctrl+alt+shift+Up
```

If you have tweaked the original shortcuts, edit your config with:
```bash
nano $(comfortable-swipe config)
```

**Comment by nakrule** [comment]
Unfortunately, I have the default configuration. I even tried to totally remove the package and install it again without success.

**Comment by Hikari9** [comment]
Hmm, that's weird. May be a problem with your desktop environment.

1. Can you run and show me output of:
    ```bash
    env | grep XDG_CURRENT_DESKTOP
    ```

2. I'm also gonna ask you to test a tool `xdotool` if it executes keyboard shortcuts properly to your machine.
    Please install
    ```bash
    sudo apt update && sudo apt install xdotool
    ```
    then run
    ```bash
    xdotool key ctrl+alt+Left
    ```
    Does your desktop switch to the left/right?
    > **Note**: you can uninstall xdotool with `sudo apt purge xdotool` if you don't want it


**EDIT**: 
    For me, my desktop is Ubuntu 18.04.2 LTS Unity so my output for 1 is:
```bash
$ env | grep XDG_CURRENT_DESKTOP
XDG_CURRENT_DESKTOP=Unity:Unity7:ubuntu
```

**Comment by nakrule** [comment]
Ok, here is my output:

    $ env | grep XDG_CURRENT_DESKTOP             
    XDG_CURRENT_DESKTOP=ubuntu:GNOME
    $ xdotool key ctrl+alt+Left     
    ^[[1;7D%       

I'm using always stock Ubuntu, zero change to my DE/WM.

**Comment by Hikari9** [comment]
Oh, for GNOME workspaces are vertical. What about
```
xdotool key ctrl+alt+Up
```
It doesn't shift your workspace down? If it doesn't, then it's a problem of `xdotool` and not `comfortable-swipe`. Either way, I'll try to help in any way I can.

According to [SonOfLars](https://askubuntu.com/users/421807/sonoflars) from this [StackOverflow thread](https://askubuntu.com/a/983827):
> Do you have a discrete graphics card? if so, try using a different graphics driver.
>
> I recently had a similar error on a clean install of Ubuntu. `xdotool` didn't seem to work, when it was definitely working on previous installations (They had been upgrades - but I wanted a fresh, clean install.)
>
> I found that switching to the **latest proprietary graphics** drivers fixed my issue. The open source driver might handle synthesised input in a different way to the proprietary one.

Try installing latest proprietary graphics driver, it might help solve the issue. Go to System Settings > Software & Updates > Additional Drivers, then update your driver if applicable (eg. intel, AMD, NVIDIA, X.org, etc)

**Comment by Hikari9** [comment]
Some additional, maybe you have mixed the keys, like `super` with `ctrl` (eg. if you're using mac). What are the actual keys you click on your keyboard to switch workspaces?

Try any one of the following:
```
xdotool key ctrl+alt+Up
xdotool key ctrl+super+Up
xdotool key alt+super+Up
```

**Comment by nakrule** [comment]
You're right, that's a problem of xdotool. For a strange reason that I don't know, the default Ubuntu shortcut to switch workspace were all deleted (that's strange because it was working when I opened this issue, while confortable-swipe was not). Thank anyway for you're support. Now it's working perfectly fine!
