### ISSUE TITLE
shortcut with page up/down

### ISSUE THREAD

**Issue by h2ku** [Hikari9/comfortable-swipe#71]
Thank you for the great app.

I was trying to assign shortcuts with `super+page up`, `super+page down`.
but didn't make it to work.
Let me know what I did wrong :)

Following is the list I tried for page down:
`page down`, `pagedown`, `pgdown`, `pagedn`, `"page down"`
env: Ubuntu 18.04

**Comment by Sartharon** [comment]
Xdotool can be finicky ...
I guess what you are looking for is
`super+Page_Up` and `super+Page_Down`

Let me know if it worked.

**Comment by h2ku** [comment]
It worked. Thanks a lot!
