### ISSUE TITLE
error: expected declaration before end of line

### ISSUE THREAD

**Issue by stoyan-stoyanov** [Hikari9/comfortable-swipe#72]
after `sudo apt-get install git libinput-tools libxdo-dev g++` and during `bash install` I get an extremely long error that ends with:
`/usr/include/c++/5/bits/stl_bvector.h:137:25: error: expected ‘{’ before ‘<’ token
/usr/include/c++/5/bits/stl_bvector.h:137:25: error: expected unqualified-id before ‘<’ token
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:27:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/include/c++/5/regex:38,
                 from ./lib/gesture/swipe_gesture.cpp:24,
                 from ./lib/comfortable_swipe:29,
                 from ./comfortable-swipe.cpp:22:
/usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:53:25: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:53:25: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:53:25: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:53:25: error: expected declaration before end of line
Installation aborted
`

System: Ubuntu 16.04
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
libxdo-dev is already the newest version (1:3.20150503.1-2)
libinput-tools is already the newest version (1.6.3-1ubuntu1~16.04.1)

**Comment by Hikari9** [comment]
g++ should be at least version 7. Try installing with `sudo apt install g++-7`
