### ISSUE TITLE
3-finger  click can work？

### ISSUE THREAD

**Issue by ioobox-adm** [Hikari9/comfortable-swipe#73]

**Comment by iberianpig** [comment]
Not now, but fusuma plugins will release soon.
I'll release tap gestures feature as fusuma-tap-plugin.

**Comment by Sartharon** [comment]
Are yo refering to a 3 finger tap? (Like the two finger tap acts like a right click/alt+click)

**Comment by Hikari9** [comment]
Closing this because the repo doesn't mess with the hardware taps, only swipes.
