### ISSUE TITLE
First gesture is slow to respond

### ISSUE THREAD

**Issue by vinicius507** [Hikari9/comfortable-swipe#74]
After a few seconds the first gesture is always slow to respond. Like it takes time to recognize the gesture. Saw issue #30 but it seems the branch was deleted. I'm using Pop_OS!

**Comment by Hikari9** [comment]
Related to #75, seems like the new Pop OS has its quirks. I'll look into this further.

In the meantime, can you paste the outputs from commands in the "Bug Reports" section in the README?

**Comment by vinicius507** [comment]
`
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.04
Release:	19.04
Codename:	disco
`

`
g++ --version
g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

`
ls -l /dev/input/event*
crw-rw---- 1 root input 13, 64 jul 11 07:17 /dev/input/event0
crw-rw---- 1 root input 13, 65 jul 11 07:17 /dev/input/event1
crw-rw---- 1 root input 13, 74 jul 11 07:17 /dev/input/event10
crw-rw---- 1 root input 13, 75 jul 11 07:17 /dev/input/event11
crw-rw---- 1 root input 13, 76 jul 11 07:17 /dev/input/event12
crw-rw---- 1 root input 13, 77 jul 11 07:17 /dev/input/event13
crw-rw---- 1 root input 13, 78 jul 11 07:17 /dev/input/event14
crw-rw---- 1 root input 13, 79 jul 11 07:17 /dev/input/event15
crw-rw---- 1 root input 13, 80 jul 11 07:17 /dev/input/event16
crw-rw---- 1 root input 13, 81 jul 11 07:17 /dev/input/event17
crw-rw---- 1 root input 13, 82 jul 11 07:17 /dev/input/event18
crw-rw---- 1 root input 13, 66 jul 11 07:17 /dev/input/event2
crw-rw---- 1 root input 13, 67 jul 11 07:17 /dev/input/event3
crw-rw---- 1 root input 13, 68 jul 11 07:17 /dev/input/event4
crw-rw---- 1 root input 13, 69 jul 11 07:17 /dev/input/event5
crw-rw---- 1 root input 13, 70 jul 11 07:17 /dev/input/event6
crw-rw---- 1 root input 13, 71 jul 11 07:17 /dev/input/event7
crw-rw---- 1 root input 13, 72 jul 11 07:17 /dev/input/event8
crw-rw---- 1 root input 13, 73 jul 11 07:17 /dev/input/event9
`

`
xinput list | grep touchpad -i
⎜   ↳ Elan Touchpad                           	id=14	[slave  pointer  (2)]
`

`
lsmod | grep hid
mac_hid                16384  0
hid_generic            16384  0
usbhid                 53248  0
i2c_hid                28672  0
hid                   126976  3 i2c_hid,usbhid,hid_generic
`

`
comfortable-swipe status
/usr/local/share/comfortable-swipe/comfortable-swipe.conf
    threshold is OK  (0.0)
        left3 is OK  (super+Down)
        left4 is OK  (shift+super+Up)
       right3 is OK  (super+Up)
       right4 is OK  (shift+super+Down)
          up3 is OK  (super)
          up4 is OK  (super+a)
        down3 is OK  (super+v)
        down4 is OK  (super+l)
autostart is ON
comfortable-swipe program is RUNNING
`

**Comment by vinicius507** [comment]
I've noticed something else now. It seems that when I use a gesture, any keyboard input after it will take a while to be registered. The opposite is also true(it seems), after any keyboard input is delivered, comfortable-swipe will take a while to respond. Don't know if that can help.

**Comment by vinicius507** [comment]
Hi, I've solved it. It is a gnome related issue. Here's the solution:
https://www.reddit.com/r/gnome/comments/84453o/delayfreezecpu_spike_when_using_the_functionmedia/

**Comment by dscarmo** [comment]
> Hi, I've solved it. It is a gnome related issue. Here's the solution:
> https://www.reddit.com/r/gnome/comments/84453o/delayfreezecpu_spike_when_using_the_functionmedia/

This also fixed the problem for me. Does not seem to be related to this repository, its a gnome bug. Also happens with volume up, volume down, mute, etc
