### ISSUE TITLE
doesn't work swipe in elementary os

### ISSUE THREAD

**Issue by anwar907** [Hikari9/comfortable-swipe#76]
lsb_release -a:
```
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 5.0 Juno
Release:	5.0
Codename:	juno
```
g++ --version:
```
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
ls -l /dev/input/event*:
```
crw-rw---- 1 root input 13, 64 Nov  3 20:38 /dev/input/event0
crw-rw---- 1 root input 13, 65 Nov  3 20:38 /dev/input/event1
crw-rw---- 1 root input 13, 74 Nov  3 20:38 /dev/input/event10
crw-rw---- 1 root input 13, 75 Nov  3 20:38 /dev/input/event11
crw-rw---- 1 root input 13, 76 Nov  3 20:38 /dev/input/event12
crw-rw---- 1 root input 13, 77 Nov  3 20:38 /dev/input/event13
crw-rw---- 1 root input 13, 66 Nov  3 20:38 /dev/input/event2
crw-rw---- 1 root input 13, 67 Nov  3 20:38 /dev/input/event3
crw-rw---- 1 root input 13, 68 Nov  3 20:38 /dev/input/event4
crw-rw---- 1 root input 13, 69 Nov  3 20:38 /dev/input/event5
crw-rw---- 1 root input 13, 70 Nov  3 20:38 /dev/input/event6
crw-rw---- 1 root input 13, 71 Nov  3 20:38 /dev/input/event7
crw-rw---- 1 root input 13, 72 Nov  3 20:38 /dev/input/event8
crw-rw---- 1 root input 13, 73 Nov  3 20:38 /dev/input/event9
```
xinput list | grep touchpad -i:
```
↳ SynPS/2 Synaptics TouchPad              	id=11	[slave  pointer  (2)]
```
lsmod | grep hid:
```
mac_hid                16384  0
```
comfortable-swipe status:
```
/usr/local/share/comfortable-swipe/comfortable-swipe.conf
    threshold is OK  (0.0)
        left3 is OK  (ctrl+alt+Right)
        left4 is OK  (ctrl+alt+shift+Right)
       right3 is OK  (ctrl+alt+Left)
       right4 is OK  (ctrl+alt+shift+Left)
          up3 is OK  (ctrl+alt+Down)
          up4 is OK  (ctrl+alt+shift+Down)
        down3 is OK  (ctrl+alt+Up)
        down4 is OK  (ctrl+alt+shift+Up)
autostart is ON
comfortable-swipe program is RUNNING
```
comfortable-swipe start: always loading

comfortable-swipe debug:
```
-event2   DEVICE_ADDED     Power Button                      seat0 default group1  cap:k
-event4   DEVICE_ADDED     Video Bus                         seat0 default group2  cap:k
-event0   DEVICE_ADDED     Power Button                      seat0 default group3  cap:k
-event1   DEVICE_ADDED     Lid Switch                        seat0 default group4  cap:S
-event10  DEVICE_ADDED     HDA NVidia HDMI/DP,pcm=3          seat0 default group5  cap:
-event11  DEVICE_ADDED     HDA NVidia HDMI/DP,pcm=7          seat0 default group5  cap:
-event12  DEVICE_ADDED     HDA NVidia HDMI/DP,pcm=8          seat0 default group5  cap:
-event13  DEVICE_ADDED     HDA NVidia HDMI/DP,pcm=9          seat0 default group5  cap:
-event7   DEVICE_ADDED     TOSHIBA Web Camera - MP: TOSHIB   seat0 default group6  cap:k
-event8   DEVICE_ADDED     HDA Intel PCH Mic                 seat0 default group5  cap:
-event9   DEVICE_ADDED     HDA Intel PCH Headphone           seat0 default group5  cap:
-event3   DEVICE_ADDED     AT Translated Set 2 keyboard      seat0 default group7  cap:k
-event5   DEVICE_ADDED     SynPS/2 Synaptics TouchPad        seat0 default group8  cap:p  size 64x32mm tap(dl off) left scroll-nat scroll-2fg-edge dwt-on
-event6   DEVICE_ADDED     Toshiba input device              seat0 default group9  cap:k
-event5   POINTER_AXIS      +2.85s	vert 9.14* horiz -0.22* (finger)
 event5   POINTER_AXIS      +2.90s	vert 22.57* horiz -3.31* (finger)
 event5   POINTER_AXIS      +2.95s	vert 35.00* horiz -4.86* (finger)
 event5   POINTER_AXIS      +2.99s	vert 37.85* horiz -0.66* (finger)
 event5   POINTER_AXIS      +3.04s	vert 38.28* horiz 3.09* (finger)
 event5   POINTER_AXIS      +3.08s	vert 35.43* horiz 2.65* (finger)
 event5   POINTER_AXIS      +3.13s	vert 28.14* horiz 2.21* (finger)
 event5   POINTER_AXIS      +3.20s	vert 8.14* horiz 1.55* (finger)
 event5   POINTER_AXIS      +3.27s	vert -0.86* horiz 1.32* (finger)
 event5   POINTER_AXIS      +3.33s	vert -5.43* horiz 1.77* (finger)
 event5   POINTER_AXIS      +3.37s	vert -20.28* horiz -3.09* (finger)
 event5   POINTER_AXIS      +3.41s	vert -39.43* horiz 5.08* (finger)
 event5   POINTER_AXIS      +3.46s	vert -33.14* horiz 13.25* (finger)
 event5   POINTER_AXIS      +3.51s	vert -36.14* horiz 11.04* (finger)
 event5   POINTER_AXIS      +3.56s	vert -31.71* horiz 7.95* (finger)
```

**Comment by neerajvashistha** [comment]
It works like a charm on elementary os
just change the config to below.
```
    threshold is     VALID (0.0)
        hold3 is    NOTSET
        hold4 is    NOTSET
        left3 is     VALID (super+Right)
        left4 is     VALID (super+alt+Right)
       right3 is     VALID (super+Left)
       right4 is     VALID (super+alt+Left)
          up3 is    NOTSET
          up4 is    NOTSET
        down3 is    NOTSET
        down4 is    NOTSET

```
Sometimes the answer is just in front of you. Thanks for all the useful commands!
@Hikari9 thank you for such an amazing repo and such a clean way to implement this. But a suggestion, if you can recognise the Linux distribution and then generate the config.

**Comment by AlwaysBeCalm** [comment]
I'm using POP!_OS 20.04 LTS and I have 2 issues:

1- I had a problem in installing comfortable-swipe, and I got this error

<pre>bash install
Old conf file found in /home/abdullah/.config/comfortable-swipe.conf
Keep the old conf file? (default: yes) [Y/n] n
Conf file will be overwritten! Are you sure? [Y/n] y
Removing previous /usr/local/bin/comfortable-swipe-buffer ... ok
Installing binaries ...
<b>./comfortable-swipe-main.cpp:</b> In function ‘<b>int main(int, char**)</b>’:
<b>./comfortable-swipe-main.cpp:95:17:</b> <font color="#75507B"><b>warning: </b></font>catching polymorphic type ‘<b>class std::invalid_argument</b>’ by value [<font color="#75507B"><b>-Wcatch-value=</b></font>]
   95 |   } catch (std::<font color="#75507B"><b>invalid_argument</b></font>) {
      |                 <font color="#75507B"><b>^~~~~~~~~~~~~~~~</b></font>
Installed: /usr/local/bin/comfortable-swipe-buffer
install: line 106: /usr/local/bin/comfortable-swipe: Permission denied
</pre>

Thankfully I solve it by changing the group and owner of /usr/local/bin to my name
<pre>sudo chgrp -R abdullah /usr/local/bin/; sudo chown -R abdullah /usr/local/bin/;
</pre>
 and install again and it installed without any errors
<pre>bash install
Old conf file found in /home/abdullah/.config/comfortable-swipe.conf
Keep the old conf file? (default: yes) [Y/n] n
Conf file will be overwritten! Are you sure? [Y/n] y
Removing previous /usr/local/bin/comfortable-swipe-buffer ... ok
Installing binaries ...
<b>./comfortable-swipe-main.cpp:</b> In function ‘<b>int main(int, char**)</b>’:
<b>./comfortable-swipe-main.cpp:95:17:</b> <font color="#75507B"><b>warning: </b></font>catching polymorphic type ‘<b>class std::invalid_argument</b>’ by value [<font color="#75507B"><b>-Wcatch-value=</b></font>]
   95 |   } catch (std::<font color="#75507B"><b>invalid_argument</b></font>) {
      |                 <font color="#75507B"><b>^~~~~~~~~~~~~~~~</b></font>
Installed: /usr/local/bin/comfortable-swipe-buffer
Installed: /usr/local/bin/comfortable-swipe
Installed: /home/abdullah/.config/comfortable-swipe.conf
Installed: /home/abdullah/.config/autostart/comfortable-swipe.desktop

Successfully installed comfortable-swipe v1.2.0
Autostart switched ON

Comfortable swipe is RUNNING in the background</pre>

Qeustion: what's the error in the cpp file?

2- the controls in the config in small letters e.g. left3  = ctrl+alt+Right and that didn't work for me, even super and shift
when I changed it to Ctrl+Alt+Right or Super+Ctrl+Left, it works great and as desired.
like:
up3    = Ctrl+Super+Down ;switch to the below workspace
down4  = Shift+Super+Up ;move the window to the above workspace

thanks

**Comment by anwar907** [comment]
thank you all,, now I have not use elementary os again:D,,,
