### ISSUE TITLE
Recognizing gestures but not triggering the action

### ISSUE THREAD

**Issue by SingularReza** [Hikari9/comfortable-swipe#82]
OS: Pop 20.04 LTS
Debug output:
```
event6   GESTURE_SWIPE_BEGIN +6.245s	3
 event6   GESTURE_SWIPE_UPDATE +6.245s	3 -0.53/-10.70 (-1.97/-40.03 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.253s	3  0.00/-9.47 ( 0.00/-35.43 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.260s	3 -0.35/-10.41 (-1.31/-38.71 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.267s	3  0.00/-9.41 ( 0.00/-34.78 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.274s	3 -0.70/-7.37 (-2.62/-27.56 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.282s	3 -0.70/-6.84 (-2.62/-25.59 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.289s	3 -0.70/-4.74 (-2.62/-17.72 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.296s	3 -0.88/-3.33 (-3.28/-12.47 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.304s	3 -0.88/-2.28 (-3.28/-8.53 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.311s	3 -0.70/-1.23 (-2.62/-4.59 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.319s	3 -0.35/-0.88 (-1.31/-3.28 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.326s	3 -0.35/-0.53 (-1.31/-1.97 unaccelerated)
 event6   GESTURE_SWIPE_UPDATE +6.333s	3 -0.17/-0.17 (-0.66/-0.66 unaccelerated)
 event6   GESTURE_SWIPE_END +6.382s	3
```

**Comment by PaulKovalov** [comment]
Same here, running Pop os 20.04

**Comment by Hikari9** [comment]
Hi, pls check out [this comment](https://github.com/Hikari9/comfortable-swipe/issues/83#issuecomment-625301101) in issue #83:

> <details> <summary> Seems like the PopOS 20.04 shortcut changed for workspaces: </summary>
> 
> ![image](https://user-images.githubusercontent.com/5916118/81308678-a1b92580-90b4-11ea-8c5f-6f486d7ff5e8.png)
>
> </details>
> 
> You can configure this by setting it in the config:
> 
> ```
> comfortable-swipe up3 = super+ctrl+Down
> comfortable-swipe down3 = super+ctrl+Up
> ```
> 
> Hope this solves your problem.

**Comment by SingularReza** [comment]
I changed back the shortcut before installing comfortable-swipe

**Comment by Hikari9** [comment]
@SingularReza  hey I think someone solved the issue.

PopOS may be sensitive with the capitalization... try these instead:

```
comfortable-swipe up3 = Super+Ctrl+Down
comfortable-swipe down3 = Super+Ctrl+Up
```

From [original comment](https://github.com/Hikari9/comfortable-swipe/issues/76#issuecomment-622815445) by @AlwaysBeCalm in issue #76.

**Comment by AbleLincoln** [comment]
I also had issues with Pop 20.04. @Hikari9's solution to capitalize works. I also had to restart after setting the config.

**Comment by nicolo-ribaudo** [comment]
This is super strange...
I'm on Ubuntu 20.04, and I couldn't make it work. I then capitalized one command, and that command started working. I "uncapitalized" it again, and it continued working.
The other commands still didn't work, but capitalizing them made them work and uncapitalizing them didn't break them.
