### ISSUE TITLE
cant get it to work after default installation

### ISSUE THREAD

**Issue by trr8018** [Hikari9/comfortable-swipe#83]
Hi,
i just switched from win10 to Pop!_OS 20.04 LTS so maybe i just made some beginner mistakes.
I have a few problems with installation of version 1.2.0.

1. Running the command `comfortable-swipe autostart` shows `/.config/autostart/comfortable-swipe.desktop` could not be found

2. I can use basic command lines like getting/setting the gestures but i cant get the gestures to work. In the following i attached the outputs of some of the commands that are mentioned in the readme.

- `lsb_release -a`
`LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	20.04
Codename:	focal
`
- `g++ --version`
`g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
`
- `ls -l /dev/input/event*`

`crw-rw---- 1 root input 13, 64 Mai  6 15:31 /dev/input/event0
crw-rw---- 1 root input 13, 65 Mai  6 15:31 /dev/input/event1
crw-rw---- 1 root input 13, 74 Mai  6 15:31 /dev/input/event10
crw-rw---- 1 root input 13, 75 Mai  6 15:31 /dev/input/event11
crw-rw---- 1 root input 13, 76 Mai  6 15:31 /dev/input/event12
crw-rw---- 1 root input 13, 77 Mai  6 15:31 /dev/input/event13
crw-rw---- 1 root input 13, 78 Mai  6 15:31 /dev/input/event14
crw-rw---- 1 root input 13, 79 Mai  6 15:31 /dev/input/event15
crw-rw---- 1 root input 13, 80 Mai  6 15:31 /dev/input/event16
crw-rw---- 1 root input 13, 81 Mai  6 15:31 /dev/input/event17
crw-rw---- 1 root input 13, 82 Mai  6 15:31 /dev/input/event18
crw-rw---- 1 root input 13, 83 Mai  6 15:31 /dev/input/event19
crw-rw---- 1 root input 13, 66 Mai  6 15:31 /dev/input/event2
crw-rw---- 1 root input 13, 67 Mai  6 15:31 /dev/input/event3
crw-rw---- 1 root input 13, 68 Mai  6 15:31 /dev/input/event4
crw-rw---- 1 root input 13, 69 Mai  6 15:31 /dev/input/event5
crw-rw---- 1 root input 13, 70 Mai  6 15:31 /dev/input/event6
crw-rw---- 1 root input 13, 71 Mai  6 15:31 /dev/input/event7
crw-rw---- 1 root input 13, 72 Mai  6 15:31 /dev/input/event8
crw-rw---- 1 root input 13, 73 Mai  6 15:31 /dev/input/event9
`
- `comfortable-swipe status`
`Autostart is MISSING
Program is STOPPED
`

- `comfortable-swipe start`
`Comfortable swipe is RUNNING in the background`

- `comfortable-swipe debug`

`event18  GESTURE_SWIPE_UPDATE +4.407s	3  0.00/ 0.05 ( 0.00/ 0.41 unaccelerated)
 event18  GESTURE_SWIPE_UPDATE +4.417s	3  0.12/-0.06 ( 0.87/-0.41 unaccelerated)
 event18  GESTURE_SWIPE_UPDATE +4.428s	3  0.00/-0.12 ( 0.00/-0.82 unaccelerated)
 event18  GESTURE_SWIPE_UPDATE +4.439s	3 -0.07/ 0.12 (-0.44/ 0.82 unaccelerated)
 event18  GESTURE_SWIPE_UPDATE +4.450s	3  0.06/-0.06 ( 0.44/-0.41 unaccelerated)
 event18  GESTURE_SWIPE_UPDATE +4.461s	3 -0.06/ 0.05 (-0.44/ 0.41 unaccelerated)
 event18  GESTURE_SWIPE_UPDATE +4.472s	3  0.00/ 0.11 ( 0.00/ 0.82 unaccelerated)
 event18  GESTURE_SWIPE_UPDATE +4.483s	3  0.13/-0.06 ( 0.87/-0.41 unaccelerated)`
This is the output for a down3 gesture.

Hope someone can help and thanks in advance.

**Comment by Hikari9** [comment]
Hi @trr8018 ! Thanks for your effort to create this issue for Pop OS.

1. The determined path for autostart is `$HOME/.config/autostart`... I haven't tried PopOS but In your comment I assume the environment variable `$HOME` is missing? Try:

```bash
export HOME=~
comfortable-swipe autostart on
```

2. The gestures seem to work but maybe workspaces are disabled? Does it work if you enter the keyboard shortcut manually? 

For PopOS keyboard shortcuts, check out this doc: https://support.system76.com/articles/pop-keyboard-shortcuts/

**Comment by Hikari9** [comment]
<details> <summary> Seems like the PopOS 20.04 shortcut changed for workspaces: </summary>

![image](https://user-images.githubusercontent.com/5916118/81308678-a1b92580-90b4-11ea-8c5f-6f486d7ff5e8.png)

</details>

You can configure this by setting it in the config:
```
comfortable-swipe up3 = super+ctrl+Down
comfortable-swipe down3 = super+ctrl+Up
```

Hope this solves your problem.

**Comment by trr8018** [comment]
Hi @Hikari9 ,
thanks for the quick reply. 

To your first point. I tried the command but nothing changed i still get this response `sed: ~comfortable-swipe/.config/autostart/comfortable-swipe.desktop could not be read: file or path not found` (i translated the message into english). Also `comfortable-swipe status` still gives me the same response.

 To your second point. If i use the shortcuts it works. I also updated the config list accordlingly but still nothing happens. I use a german keyboard but i dont think that should matter as i copied the shortcuts from the settings.

Issue #82  seems like the same problem or at least a very similar one. If it turns out to be the case i could close this issue.

**Comment by Hikari9** [comment]
@trr8018 , if you're using German keyboard, this might be related to the foreign keyboard problem. Sounds similar to the unsolved issue #75. 

Quoting from johnvanham:
> I am experiencing this too on Pop!_OS 19.10
> 
> I have two languages set up, BOTH are English (UK), however one (the first) is for my laptop keyboard layout which is a Dell Inspiron 7590, and the second is for my Apple bluetooth keyboard with the language English (UK, Macintosh) (set as second language).
> 
> If I have the first one selected, gestures are fast. If I have the second selected, gestures are slow - including how long it takes before the gestures shows up in terminal after running comfortable-swipe start. Also, just using xdotool in the terminal there is a delay after each command. So it's definitely something going on in xdotool. Or affecting both comfortable-swipe and xdotool.
> 
> I tried libinput-gestures first and had the same problem. Thanks to this issue though, I know why!
> 
> If some sort of workaround could be found that would be amazing.
> 
> Interestingly, if I swap the order of the languages in 'Input Sources' under 'Region & Language' in settings, the gestures are slow with the second language selected, even though that used to be the first. So it's something to do with it not being the first language, rather than which language it is.

If you swap keyboard with English and it works, then it is the same issue with PopOS and `xdotool` and not comfortable-swipe... The workaround so far is swapping input sources please try it out.

Thanks

**Comment by Hikari9** [comment]
@trr8018 hey I think someone solved the issue.

PopOS may be sensitive with the capitalization... try these instead:

```
comfortable-swipe up3 = Super+Ctrl+Down
comfortable-swipe down3 = Super+Ctrl+Up
```

From [original comment](https://github.com/Hikari9/comfortable-swipe/issues/76#issuecomment-622815445) by @AlwaysBeCalm in issue #76.

**Comment by trr8018** [comment]
Still have the problem with the english keyboard and capitalization doesnt change anything.
I dont think comfortable-swipe gets started properly. `comfortable-swipe status` always gives me the response Autostart missing; Programm stopped

**Comment by Hikari9** [comment]
That's very unusual... Somewhat last resort try the following command:

 ```
 comfortable-swipe debug | comfortable-swipe buffer
 ```
 Swiping should show `SWIPE right3`, `SWIPE left3` etc.

1. If the swipe WORKS PERFECTLY, manually add the command to startup. Search for `Startup Applications` in Dash and add the above as "Command". If you could find out the autostart folder for System76 of the new version for me that would be helpful for updates.

1. If the command DOES NOT EXECUTE, I need the output of the following:
    ```
    which libinput
    which comfortable-swipe
    which comfortable-swipe-buffer
    libinput --version
    ```

1. If the command EXECUTES but `SWIPE xxx` DOES NOT show, then this is a driver problem. I'll need more time to replicate.

1. If the command EXECUTES and `SWIPE xxx` SHOWS but doesn't TRIGGER any action, kindly paste the output of the following:

    ```
    comfortable-swipe config list
    ```

Thanks for your patience!

**Comment by willc** [comment]
Just updated to Pop_OS 20.04 and came here to try comfortable-swipe because the libinput-gestures package stopped working after the update to the OS.

I am having similar problems, but when I run this:
`
comfortable-swipe debug | comfortable-swipe buffer`

It says this:
`
error: config /root/.config/comfortable-swipe.conf`

Edit to add: I am not logged in as the root user

Everything else appears to be on and installed correctly, and I can see the appropriate responses to gestures when I am simply in debug mode.

**Comment by AlwaysBeCalm** [comment]
@willc 
have you installed it with root permissions?
sudo bash install

**Comment by willc** [comment]
> @willc
> have you installed it with root permissions?
> sudo bash install

The first time I installed it it gave me this:

```
$ bash install
Installing binaries ...
[sudo] password for willc: 
Installed: /usr/local/bin/comfortable-swipe-buffer
install: line 101: /usr/local/bin/comfortable-swipe: Permission denied
```

So I figured I needed to do 'sudo bash install' and tried it that way.
I have since uninstalled it and tried to reinstall it without sudo and am still getting the install error above.

**Comment by AlwaysBeCalm** [comment]
@willc 
See this
https://github.com/Hikari9/comfortable-swipe/issues/76#issuecomment-622815445

**Comment by napsterv** [comment]
> @willc
> See this
> [#76 (comment)](https://github.com/Hikari9/comfortable-swipe/issues/76#issuecomment-622815445)

It's 2AM and I was stuck. Thanks a lot! Works perfectly now.

**Comment by AlwaysBeCalm** [comment]
@Hikari9 
Thanks a lot for the tool

but I also got the same error in Ubuntu 20.04 LTS

<pre>bash install 
Old conf file found in /home/abdullah/.config/comfortable-swipe.conf
Keep the old conf file? (default: yes) [Y/n] n
Conf file will be overwritten! Are you sure? [Y/n] y
Removing previous /usr/local/bin/comfortable-swipe-buffer ... ok
Installing binaries ...
Installed: /usr/local/bin/comfortable-swipe-buffer
install: line 102: /usr/local/bin/comfortable-swipe: Permission denied</pre>

and solve it be changing the permission
<pre>sudo chmod go+w -R bin</pre>

solve this please, because others might install it with root
Thanks :rose:

**Comment by trr8018** [comment]
@Hikari9 
Thanks a lot #76 worked for me. Now `comfortable-swipe status` gives me the correct output and my gestures work as intended.

Im going to close this issue now, thanks again.

**Comment by Hikari9** [comment]
@AlwaysBeCalm Thanks for this. I guess the group permissions are necessary for the new OS's.

But I cannot do a broad

```
sudo chmod go+w -R bin
```

because that will open up group permissions for ALL bin executables.
Adding the following for the next patch:

```
sudo chmod go+wx /usr/local/bin/comfortable-swipe*
```

Thanks everyone :rocket:
