### ISSUE TITLE
Error during install: cannot move file

### ISSUE THREAD

**Issue by XimmersiveX** [Hikari9/comfortable-swipe#89]
Ubuntu 20.04 LTS
Codename: focal

v: cannot move '/tmp/tmp.q2LmOq8kBE' to '/usr/local/bin/comfortable-swipe-buffer': No such file or directory

Update:
I created the bin directory with chmod 775 and the script copied comfortable-swipe-buffer* into there.

But now when running bash install as normal user I get:

install: line 101: /usr/local/bin/comfortable-swipe: Permission denied

and if I try as sudo:

install: line 130: /root/.config/autostart/comfortable-swipe.desktop: No such file or directory

No root folder so that's understandable but at a loss as to where to go from here.

**Comment by jerryjean** [comment]
Same issue here.

I was able to get it to work by temporarily setting the ownership of /usr/local/bin

`sudo chown -R [my_user] /usr/local/bin`

**Comment by XimmersiveX** [comment]
Thank you @jerryjean that solved my problem and the program installed and starts properly.

Still doesn't actually work as intended on my system though. I think it may have something to do with this laptop having a touchscreen also. And I can use 4 finger swipe on it to change work spaces.

Using the debug mode I can see that my trackpad does handle 3 and 4 finger inputs but no clue why I can't get this to work. Going to try something else for now. Thanks for the help.
