### ISSUE TITLE
Swipe back

### ISSUE THREAD

**Issue by dhruvdutt** [Hikari9/comfortable-swipe#9]
Can we allow swipe back without releasing the touchpad.
Let's say I'm doing 3-fingers swipe and switching to a new workspace to look over something.
Now, if I need to switch back to the first workspace immediately, I cannot do it until I release all three fingers from the touchpad and put it on and do the 3-fingers swipe again.

This feature is present in macOS. It would be awesome to have it in this lib too. BTW, awesome work! :rocket:

**Comment by Hikari9** [comment]
Thanks! Sounds like a good feature to me. Please check out PR #10 and comment if it suits your needs :)

**Comment by dhruvdutt** [comment]
That was quick! :100: :fire:
